Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -94,8 +94,8 @@ jobs:
           cat << EOF > conf
           https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
             out=lspatch.jar
-          https://d.apkpure.com/b/XAPK/jp.naver.line.android?versionCode=${{ env.line_ver_code }}&nc=arm64-v8a&sv=28
-           out=original-arm64-v8a.apk
+          https://d.apkpure.com/b/XAPK/jp.naver.line.android?versionCode=141910383&nc=arm64-v8a&sv=28
+            out=original-arm64-v8a.apk
           https://line-android-universal-download.line-scdn.net/line-14-19.1.apk
             out=original-armeabi-v7a.apk
           https://www.apkmirror.com/apk/line-corporation/line/line-14-19-1-release/line-calls-messages-14-19-1-android-apk-download/download/?key=168fc2e8af120111c350b2943dd89a3841f1546b
@@ -115,16 +115,28 @@ jobs:
           # Patch arm64-v8a APK
           echo "Patching APK for arm64-v8a ..."
           java -jar lspatch.jar "original-arm64-v8a.apk" -m "app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
+          if [ $? -ne 0 ]; then
+            echo "ERROR: Failed to patch arm64-v8a APK." >&2
+            exit 1
+          fi
           mv "patched-apk-output.apk" "line-${{ env.line_ver }}-arm64-v8a.apk"
 
           # Patch armeabi-v7a APK
           echo "Patching APK for armeabi-v7a..."
           java -jar lspatch.jar "original-armeabi-v7a.apk" -m "app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
+          if [ $? -ne 0 ]; then
+            echo "ERROR: Failed to patch armeabi-v7a APK." >&2
+            exit 1
+          fi
           mv "patched-apk-output.apk" "line-${{ env.line_ver }}-armeabi-v7a.apk"
 
           # Patch both architectures APK
           echo "Patching APK for both architectures..."
           java -jar lspatch.jar "original-both.apk" -m "app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
+          if [ $? -ne 0 ]; then
+            echo "ERROR: Failed to patch both architectures APK." >&2
+            exit 1
+          fi
           mv "patched-apk-output.apk" "line-${{ env.line_ver }}-both.apk"
 
           # Verify generated APKs
