Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -95,8 +95,8 @@ jobs:
           https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
             out=lspatch.jar
           https://d.apkpure.com/b/XAPK/jp.naver.line.android?versionCode=${{ env.line_ver_code }}&nc=arm64-v8a&sv=28
-            out=original-arm64-v8a.apk
-          https://line-android-universal-download.line-scdn.net/line-14.19.1.apk
+           out=original-arm64-v8a.apk
+          https://line-android-universal-download.line-scdn.net/line-14-19.1.apk
             out=original-armeabi-v7a.apk
           https://www.apkmirror.com/apk/line-corporation/line/line-14-19-1-release/line-calls-messages-14-19-1-android-apk-download/download/?key=168fc2e8af120111c350b2943dd89a3841f1546b
             out=original-both.apk
@@ -104,7 +104,13 @@ jobs:
 
           # Download all files using aria2c
           echo "Downloading APKs and LSPatch tool..."
-          aria2c --no-conf -x16 -s16 -R -m0 -V --async-dns=false -iconf=conf
+          aria2c --no-conf -x16 -s16 -R -m0 -V --async-dns=false --conf=conf
+
+          # Check if the download was successful
+          if [ $? -ne 0 ]; then
+            echo "ERROR: Failed to download files." >&2
+            exit 1
+          fi
 
           # Patch arm64-v8a APK
           echo "Patching APK for arm64-v8a ..."
