Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,12 +1,30 @@
-name: Build and Release
+name: Build
 
 on:
-  release:
-    types: [created]
+  push:
+    paths:
+      - '.github/workflows/build.yml'
+      - 'app/**'
+      - 'gradle/**'
+      - '*.gradle'
+      - '*.properties'
+  pull_request:
+  workflow_dispatch:
+    inputs:
+      release:
+        description: 'Release'
+        type: boolean
+        required: true
+        default: false
+      lspatch:
+        description: 'LSPatch'
+        type: boolean
+        required: true
+        default: false
 
 jobs:
   build:
-    name: Build and Patch
+    name: Build
     runs-on: ubuntu-latest
     permissions:
       contents: write
@@ -18,7 +36,7 @@ jobs:
       - name: Set environments
         run: |
           {
-            echo "version=${{ github.event.release.tag }}"
+            echo "version=v$(grep versionName app/build.gradle | awk '{print $2}' | tr -d \")"
             echo "line_ver_code=$(grep HOOK_TARGET_VERSION app/build.gradle | awk '{print $4}' | tr -d \'\")"
             echo "commit=$(echo ${{ github.sha }} | cut -c-7)"
             echo "repo=$(echo ${GITHUB_REPOSITORY#$GITHUB_REPOSITORY_OWNER/})"
@@ -36,56 +54,99 @@ jobs:
       - name: Setup Gradle
         uses: gradle/actions/setup-gradle@v4
 
+      - name: Get previous version name
+        uses: oprypin/find-latest-tag@v1.1.2
+        if: github.event.inputs.release == 'true'
+        id: previous
+        with:
+          repository: ${{ github.repository }}
+          releases-only: true
+
+      - name: Release check
+        if: github.event.inputs.release == 'true'
+        run: |
+          if [ "${{ secrets.STORE_FILE }}" == "" ]; then
+            echo -e "\nERROR!\nTo release, you need to set up a signing key!\n"
+            exit 1
+          fi
+          if [ "${{ steps.previous.outputs.tag }}" == "${{ env.version }}" ]; then
+            echo -e "\nERROR!\nThe same tag already exists!\n"
+            exit 1
+          fi
+
       - name: Build with Gradle
         run: |
-          echo "${{ secrets.STORE_FILE }}" | base64 -d > app/release.jks
-          export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
-          export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
-          export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
-          ./gradlew assembleRelease --no-daemon --stacktrace
-          cp -f app/build/outputs/apk/release/app-release.apk ${{ env.repo }}-${{ env.version }}.apk
+          if [ "${{ inputs.release }}" == "true" ]; then
+            echo "${{ secrets.STORE_FILE }}" | base64 -d > app/release.jks
+            export STORE_PASSWORD="${{ secrets.STORE_PASSWORD }}"
+            export KEY_ALIAS="${{ secrets.KEY_ALIAS }}"
+            export KEY_PASSWORD="${{ secrets.KEY_PASSWORD }}"
+            ./gradlew assembleRelease --no-daemon --stacktrace
+            cp -f app/build/outputs/apk/release/app-release.apk ${{ env.repo }}-${{ env.version }}.apk
+          else
+            ./gradlew assembleDebug --no-daemon --stacktrace
+          fi
 
-      - name: Patch for arm64-v8a
+      - name: LSPatch for arm64-v8a
+        if: github.event.inputs.lspatch == 'true'
         run: |
           apk_url="https://d.apkpure.com/b/XAPK/jp.naver.line.android?versionCode=${{ env.line_ver_code }}&nc=arm64-v8a&sv=28"
-          echo "Patching for arm64-v8a..."
-          echo "https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar" > conf
-          echo "$apk_url" >> conf
+          cat << EOF > conf
+ https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
+            out=lspatch.jar
+          $apk_url
+            out=line-${{ env.line_ver }}-arm64-v8a.apk
+          EOF
+          echo "Downloading APK for arm64-v8a..."
           aria2c --no-conf -x16 -s16 -R -m0 -V --async-dns=false -iconf
-          java -jar lspatch.jar "line-${{ env.line_ver }}.apk" -m "app/build/outputs/apk/release/app-release.apk" -l 2 -v
-          mv "line-${{ env.line_ver }}-lspatched.apk" "LINE-${{ env.line_ver }}-arm64-v8a-lspatched.apk"
+          echo "Patching LIME for arm64-v8a..."
+          java -jar lspatch.jar "line-${{ env.line_ver }}-arm64-v8a.apk" -m " app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
 
-      - name: Patch for armeabi-v7a
+      - name: LSPatch for armeabi-v7a
+        if: github.event.inputs.lspatch == 'true'
         run: |
           apk_url="https://line-android-universal-download.line-scdn.net/line-14.19.1.apk"
-          echo "Patching for armeabi-v7a..."
-          echo "https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar" > conf
-          echo "$apk_url" >> conf
+          cat << EOF > conf
+ https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
+            out=lspatch.jar
+          $apk_url
+            out=line-${{ env.line_ver }}-armeabi-v7a.apk
+          EOF
+          echo "Downloading APK for armeabi-v7a..."
           aria2c --no-conf -x16 -s16 -R -m0 -V --async-dns=false -iconf
-          java -jar lspatch.jar "line-${{ env.line_ver }}.apk" -m "app/build/outputs/apk/release/app-release.apk" -l 2 -v
-          mv "line-${{ env.line_ver }}-lspatched.apk" "LINE-${{ env.line_ver }}-armeabi-v7a-lspatched.apk"
+          echo "Patching LIME for armeabi-v7a..."
+          java -jar lspatch.jar "line-${{ env.line_ver }}-armeabi-v7a.apk" -m "app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
 
-      - name: Patch for both architectures
+      - name: LSPatch for both architectures
+        if: github.event.inputs.lspatch == 'true'
         run: |
           apk_url="https://www.apkmirror.com/apk/line-corporation/line/line-14-19-1-release/line-calls-messages-14-19-1-android-apk-download/download/?key=168fc2e8af120111c350b2943dd89a3841f1546b"
-          echo "Patching for both architectures..."
-          echo "https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar" > conf
-          echo "$apk_url" >> conf
+          cat << EOF > conf
+ https://github.com/JingMatrix/LSPatch/releases/latest/download/lspatch.jar
+            out=lspatch.jar
+          $apk_url
+            out=line-${{ env.line_ver }}-both.apk
+          EOF
+          echo "Downloading APK for both architectures..."
           aria2c --no-conf -x16 -s16 -R -m0 -V --async-dns=false -iconf
-          java -jar lspatch.jar "line-${{ env.line_ver }}.apk" -m "app/build/outputs/apk/release/app-release.apk" -l 2 -v
-          mv "line-${{ env.line_ver }}-lspatched.apk" "LINE-${{ env.line_ver }}-both-lspatched.apk"
+          echo "Patching LIME for both architectures..."
+          java -jar lspatch.jar "line-${{ env.line_ver }}-both.apk" -m "app/build/outputs/apk/debug/app-debug.apk" -l 2 -v
 
-      - name: Release arm64-v8a
-        run: |
-          echo "Releasing arm64-v8a version..."
-          gh release create ${{ env.version }} LINE-${{ env.line_ver }}-arm64-v8a-lspatched.apk --title "Release ${{ env.version }} (arm64-v8a)" --notes "## 対応するLINEのバージョン\n${{ env.line_ver }}"
+      - name: Upload Patched LINE APKs
+        uses: actions/upload-artifact@v4
+        if: github.event.inputs.lspatch == 'true'
+        with:
+          name: LINE-${{ env.line_ver }}@${{ env.commit }}
+          path: line-${{ env.line_ver }}-*-lspatched.apk
+          if-no-files-found: error
 
-      - name: Release armeabi-v7a
+      - name: Release
+        if: github.event.inputs.release == 'true'
         run: |
-          echo "Releasing armeabi-v7a version..."
-          gh release create ${{ env.version }} LINE-${{ env.line_ver }}-armeabi-v7a-lspatched.apk --title "Release ${{ env.version }} (armeabi-v7a)" --notes "## 対応するLINEのバージョン\n${{ env.line_ver }}"
-
-      - name: Release both architectures
-        run: |
-          echo "Releasing both architectures version..."
-          gh release create ${{ env.version }} LINE-${{ env.line_ver }}-both-lspatched.apk --title "Release ${{ env.version }} (both)" --notes "## 対応するLINEのバージョン\n${{ env.line_ver }}"
+          echo "Releasing version ${{ env.version }}..."
+          gh release create ${{ env.version }} \
+            line-${{ env.line_ver }}-arm64-v8a.apk \
+            line-${{ env.line_ver }}-armeabi-v7a.apk \
+            line-${{ env.line_ver }}-both.apk \
+            --title "Release ${{ env.version }}" \
+            --notes "## 対応するLINEのバージョン\n${{ env.line_ver }}\n\n### 差分\nhttps://github.com/${{ github.repository }}/compare/${{ steps.previous.outputs.tag }}...${{ env.version }}\n\n### パッチファイル\nline-${{ env.line_ver }}-arm64-v8a.apk\nline-${{ env.line_ver }}-armeabi-v7a.apk\nline-${{ env.line_ver }}-armeabi-v7a +arm64 .apk"
